### ISSUE TITLE
Add endorsements

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#103]
e.g.

https://x.com/schickling/status/1832361798130954335
https://x.com/raymmar_/status/1832464000996548806
https://x.com/xdamman/status/1837021472499343492

Others?

Let's also include ecosystem partner endorsements, e.g., OSI, OC, Ruby Central, etc.

Should rotate one on the homepage and collect multiple on an /endorsements page.

**Comment by Delta456** [comment]
Feel free to add my testimonial.

OSS Pledge is a gateway to sponsoring open source developers who are working hard to develop projects for the ecosystem

**Comment by chadwhitacre** [comment]
Thank you @Delta456. 🙏

**Comment by chadwhitacre** [comment]
We have permission to add Andreas' quote. Here's a design mock from Steven.

<img width=200 src=https://github.com/user-attachments/assets/3668255f-b0dd-4944-87ca-8ae13a120caa> <img width=200 src=https://github.com/user-attachments/assets/59469bed-e8b0-4462-b438-a98a5fd565a3>

**Comment by vladh** [comment]
@chadwhitacre Love it. What if we had minor variations to break the regularity? Right now all testimonials have an “ open quote at the top left. Maybe the middle one could have a ” closed quote at the bottom right, for example. Just an idea. 

Let me know when you’re happy with the design and I can implement it ASAP.

**Comment by chadwhitacre** [comment]
We now also have permission from Johannes and Raymmar.

Honestly I think a shorter quote from each would have more impact. Something like:

"I can't overstate how excited I am about this. ❤️" —Johannes
"Every VC funded company post series B should do this 🔥" —Andreas
"Great initiative. Much needed and vital for the next step of internet growth 💪🏽" —Raymmar

Link for full context.

**Comment by Delta456** [comment]
What's the need to link? I think that's enough validation we have there.

**Comment by chadwhitacre** [comment]
The link is so people can follow up to check the original source and context.

**Comment by Delta456** [comment]
Ok, makes sense

**Comment by vladh** [comment]
@chadwhitacre Are we still iterating on the design or shall I go ahead and get this implemented?

**Comment by chadwhitacre** [comment]
Go for it. :)

**Comment by chadwhitacre** [comment]
I've [asked](https://x.com/chadwhitacre_/status/1841583586283061693) Xavier for permission, we are good to go from Johannes and Raymmar.

**Comment by vladh** [comment]
Sounds good, do we have any endorsements we can share from ecosystem partners, or not yet?

**Comment by chadwhitacre** [comment]
I expect we'll be able to pull some from the blog posts that are supposed to go out on Tuesday.
