### ISSUE TITLE
Run promotional campaign

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#11]
We are launching a major promotional campaign for the Pledge on October 8.

### Components

1. SF OOH (out-of-home, i.e., billboards) campaign
    - We're live in SF from October 7 through Nov 3 (for billboards, bus sides and shelters are likely to linger for much longer).
    - Art is due September 16.
2. NYC Nasdaq jumbotron
    - art is due Oct 1 (logos on #5 due Sept 24)
4. digital

**Comment by chadwhitacre** [comment]
Fwiw we're planning to use the osspledge.com URL on the billboards since it's shorter, it currently redirects to opensourcepledge.com.

**Comment by chadwhitacre** [comment]
I'll let @selviano weigh in but I expect we'll want to also weight logos by recognizability. The main point is to grab people's attention and validate the Pledge as a thing worth investigating and joining. Logos with a lot of brand equity will help the most with that, and honestly smaller companies will benefit from the association as well.

**Comment by chadwhitacre** [comment]
We've gone through two rounds of concept creation with Sentry's in-house creative team. We are dialing in on a campaign with three variations on the theme of calling out leadership at companies who do not pay maintainers, along these lines (final might be slightly different):

- CEO - Chief Excuses Officer
- CFO - Chief Freeloading Officer
- CTO - Chief Taking Officer

**Comment by vladh** [comment]
@chadwhitacre I think it's a great idea to put pressure on companies, but I'm concerned that this wording might be too antagonising and drive away executives who would otherwise contribute, because as soon as they're personally shamed by a movement they might not want to interact with it.

Maybe focusing on the financials would be a good approach. For example, NVIDIA probably has around 15,000 developers, and they brought in $33 billion last fiscal year. Making the pledge would cost them $30 million per year, which is 0.00009% of their income. I think that's more shameful than being called names — it's shameful because it's unfair and unwise, and harms the ecosystem they depend on.

Every other company is less valuable than NVIDIA, but even if the number was 0.9% it would be shameful and unwise.

**Comment by chadwhitacre** [comment]
We talked about this on the weekly steering call. @vladh brought up [tbfighters.org](https://tbfighters.org/) as an example of an activism campaign with some parallels where the change was driven through a more positive tone.

> as soon as they're personally shamed by a movement

It does seem here like we wouldn't be shaming specific individuals or companies with this campaign. Its "CEO / CFO / CTO" in the abstract. Another difference is that this is only for the SF OOH campaign, we're not proposing to carry this campaign through on osspledge.com itself or in other channels.

@selviano is just getting back into the swing of things post-vacation, let's see how conversations play out at Sentry internally this week.

**Comment by vladh** [comment]
> It does seem here like we wouldn't be shaming specific individuals or companies with this campaign. Its "CEO / CFO / CTO" in the abstract.

Got it, I think that makes it way better.

**Comment by chadwhitacre** [comment]
Expectation is assets to Nasdaq by EOD on Oct 1.

**Comment by chadwhitacre** [comment]
Most logos we can comfortably fit on Nasdaq even w/ NASCAR style is ~15.

**Comment by chadwhitacre** [comment]
We've got [5 early adopters](https://github.com/opensourcepledge/osspledge.com/issues/5#issuecomment-2284827223) in process of getting signed up, I think we should be able to get another 5 or 10 onboarded "pretty quickly" once we resolve #45.

**Comment by chadwhitacre** [comment]
Conclusions from the digital promo meeting:

1. Our main CTA on the website will be, "Schedule a call to learn more about the Pledge."
2. Audiences:
    1. Primary audience is leadership with budget approval at Series A to C companies.
    1. Secondary audience is wider dev/tech industry to build upward pressure/incentive.
5. Tactics:
    1. budget: 25 to 50k
    1. geo-target SF
    1. channels: leaning towards LinkedIn and Meta for leadership reach
    1. digital will launch either with OOH or before (pending website ship)

**Comment by chadwhitacre** [comment]
We have OOH designs! Here are the final drafts of the three SF billboards, featuring what Sentry's creative team is calling "mooch monsters." The bus shelters and digital ads will be variations of these. I believe the Nasdaq jumbotron will not have a mooch monster (yes, @selviano?).

![ceo](https://github.com/user-attachments/assets/b9b36601-7f9e-47d9-b26b-559258a8f076)

![cfo](https://github.com/user-attachments/assets/11090ebc-5490-41ca-b588-8c501c3526f3)

![cto](https://github.com/user-attachments/assets/57d4ce1e-f77e-496d-84d9-01e7d45cff3e)

Here's a first look at what folks will see if/when they visit the website (more on #6):

![oss-home](https://github.com/user-attachments/assets/1723d631-cf99-4190-ba59-b76eeb5ae4f8)

**Comment by selviano** [comment]
correct, Nasdaq will be a discrete design, featuring our partner logos and congratulating them all on the launch/commitment

**Comment by chadwhitacre** [comment]
@selviano is putting together a promo packet to include:
- README with timeline and messaging
- blog and email templates, 

@Ethan-Arrowood What do you think of sending an email to foundation launch partners next week with the promo packet and invitation to market with us on Oct 8 and following? Here's an initial list of likelies:

1. django
2. ruby central
3. freebsd
4. osi
5. osc
6. openjs
7. numfocus
8. rust
9. python
10. apache

P.S. I started https://github.com/openjs-foundation/sustainability-collab-space/issues/12 to work it through with OpenJS.

**Comment by chadwhitacre** [comment]
@Ethan-Arrowood @selviano and I had a call to workshop this. We're aiming to update our partner interest email list and send out a launch coordination email by EOW at the latest. Here's our [working doc 🔒](https://docs.google.com/document/d/1Z9-lKEJtBVQZaCqvLXxajgZxHA2sX32AbFNBmup-nFs/edit?usp=sharing).

**Comment by chadwhitacre** [comment]
They tell me ads are live on multiple platforms. I'm gonna close this out. [The horse is out of the gate](https://x.com/zeeg/status/1843321451358912741)!
