### ISSUE TITLE
Add a slightly more comprehensive way of monitoring JSON files

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/opensourcepledge.com#113]
What if a member's JSON file starts 404ing? Should they stop showing up on the website? Should they stay there, but with a warning label? Should we receive an alert, so that we can contact the member?

What if a member doesn't add an annual report for a long time? Should we receive an alert, so that we can ask them for one?

**Comment by voxpelli** [comment]
One flow I have started using is to use scheduled GitHub Actions to automatically raise PR:s with such changes.

Examples:

1. https://github.com/SocketDev/socket-sdk-js/pull/228 (see [workflow](https://github.com/SocketDev/socket-sdk-js/blob/9999f401c157cc8bc7cb9c381c46400854bf052a/.github/workflows/generate.yml#L17-L28))
2. https://github.com/neostandard/neostandard/pull/172 (see [workflow](https://github.com/neostandard/neostandard/blob/main/.github/workflows/sync-refresh.yml))
3. https://github.com/voxpelli/tsconfig/pull/59 (see [workflow](https://github.com/voxpelli/tsconfig/blob/621982fce7a18c8dbe4b8c5f8cd7fc34ae9c5289/.github/workflows/sync-dependents.yml#L18-L32) and especially [the reusable one](https://github.com/voxpelli/tsconfig/blob/621982fce7a18c8dbe4b8c5f8cd7fc34ae9c5289/.github/workflows/sync-reusable.yml), which is the latest iteration of these three)

I could try to lend a hand in this if you are interested

**Comment by vladh** [comment]
Thanks @voxpelli! A workflow would be nice, but I think it needs to send an email or similar — if the JSON file is down on a member's website, we don't have the ability to fix that, so all we can do is let them know.

**Comment by chadwhitacre** [comment]
(Simplifying labels fwiw)

**Comment by chadwhitacre** [comment]
I'm generally in favor of solving this one way or another.

> If one of the checks fails, the action would send an email to all Open Source Pledge maintainers.

Won't a PR like @voxpelli suggests naturally result in an email (or other notification) to Pledge maintainers?

**Comment by vladh** [comment]
> Won't a PR like @voxpelli suggests naturally result in an email (or other notification) to Pledge maintainers?

For sure, I'm just not quite seeing what suggested changes to our repo the PR would contain.

**Comment by chadwhitacre** [comment]
I guess removing the company from `members.csv` could make sense? Bot proposes removing, we then follow up to see if that is the right decision?

**Comment by vladh** [comment]
Hmm, I don't think so, because:

1. We could use a system that alerts us before action is required, so that we can give some notice. For example, if a member has 1 month left to submit the next annual report, this is not cause for removal, but a notification should still be sent.
2. It would be nice to preserve goodwill by addressing lapsed memberships with inquiry/conversation, not an automated removal “one strike and you're (automatically proposed to be) out” policy.

**Comment by chadwhitacre** [comment]
My thinking was that using GH notification flow is low-hanging fruit, and it's easy enough to close (rather than merge) the PR if/when the member re-ups.

**Comment by chadwhitacre** [comment]
Having the PR also gives us a natural place to keep track of pending renewals and provide updates as we reach out.

**Comment by vladh** [comment]
Got it, then let's have it open an issue instead of a PR — best of both worlds! If any action is taken we can mention the issue as related.

**Comment by chadwhitacre** [comment]
Perfect. :) 🎉
