### ISSUE TITLE
Get Member logos in right format for the NASDAQ Tower

### ISSUE THREAD

**Issue by selviano** [opensourcepledge/opensourcepledge.com#115]
@vladh surfaced the issue of promising members space on the NASDAQ tower then potentially running out of room. 

The challenge is, the NASDAQ tower has a unique design, with dead spots for windows in the building: 
<img width="403" alt="image" src="https://github.com/user-attachments/assets/3883532c-a2ae-4b61-9793-6e82b9245ba5">

I spoke with the Sentry design team, and they made some quick mockups of potential options, featuring up to 24 partners. 
![image_720](https://github.com/user-attachments/assets/1656bd66-ea77-4c3d-ba55-3f5b3997fec4)
![image_720](https://github.com/user-attachments/assets/c4aa4e06-09a7-44fb-bae7-9415e57947d8)
![image_720](https://github.com/user-attachments/assets/a9094bca-482f-41cf-9451-7b0235c287b5)

The deadline for NASDAQ Tower inclusion that we've communicated to Members is 9/24. Because we don't yet know the final number of companies we'll have by then, we don't know which format we'll use, which would dictate what kind of logos we request from members (square? Rectangular? Wordmark?) So, I'd like to request logo variants/options from them to fit whatever layout we end up choosing. (Rather than scrambling last minute to request whatever format we decide upon from each of them). 

I'm working with design to get our final ask, but then we'll need to communicate to members to submit the logo variants to us by 9/24. Should we do this as a one off communication, or should we have a broader communication or even live "orientation" session to go over things like day of promotion etc? Also, we could include these details as a section in the Partner Promotion Kit, but we'd still want to go out of our way to communicate it. 

Open to ideas!

**Comment by selviano** [comment]
OK here's the specifics of which logos we'll ask for: 
1) Glyph/icon in square area
2) full name/wordmark in a wide rectangle area. 

Both files should have transparent background and/or as a vector file (like SVG or AI), and min width for both of 400px.

Expect the logos to be on a dark background, so give us the light version of your  logo (or expect us to make it all white).

Here are examples of Sentry's logo in these formats: (white on white so might be invisible on GitHub)
![sentry-glyph-light-400x367](https://github.com/user-attachments/assets/aeb16b01-e96c-4c85-b09a-7f3370f0cd36)
![sentry-wordmark-light-400x119](https://github.com/user-attachments/assets/ad75a4ba-f952-4352-9999-98bf4a54e650)

**Comment by voxpelli** [comment]
A somewhat geeky question from
an intrigued bystander:

In the example with 24 partners, what would the actual resolution on the nasdaq screen be for that square?

I'm thinking such a large screen probably has quite a low DPI and depending on the resolution one would need to pick the right format of a logo for it to remain legible

**Comment by selviano** [comment]
that’s a great question, while it’s highly unlikely we’ll hit 24 partners, this question still applies to the other format options. I’ve put in a request about the screen resolution/specs with my contacts at NASDAQ and will respond here with what I learn…

**Comment by vladh** [comment]
This is a checklist of members we have sufficiently varied logos for:

- [ ] Sentry
- [ ] Antithesis
- [ ] StackBlitz
- [ ] Astral
- [ ] Scalar
- [ ] Frontend Masters
- [ ] Emerge Tools
- [ ] Browserbase
- [ ] Private Packagist
- [ ] Val Town
- [ ] GitButler
- [ ] Rector
- [ ] Keygen
- [ ] HTTP Toolkit
- [ ] Chief Tools

**Comment by vladh** [comment]
@selviano Except for Rector and Chief Tools, everyone has given us at the very least one logomark and one logomark + wordmark. 🎉  I think that's enough, but let me know if I should contact members for anything else.

**Comment by selviano** [comment]
thanks @vladh! 

Are these in the format that design requested (see below)? Also, are they stored in some central location somewhere?

> 1. Glyph/icon in square area
> 2. full name/wordmark in a wide rectangle area.
> 
> Both files should have transparent background and/or as a vector file (like SVG or AI), and min width for both of 400px.
> 
> Expect the logos to be on a dark background, so give us the light version of your logo (or expect us to make it all white).

**Comment by vladh** [comment]
@selviano I double-checked those requirements:

- [x] Sentry — N/A
- [x] Antithesis — ✅ 
- [x] StackBlitz — ✅, but I asked for an additional version to be sure
- [x] Astral — ✅
- [x] Scalar — ✅ 
- [x] Frontend Masters — ✅ 
- [x] Emerge Tools — ✅
- [x] Browserbase — ✅ 
- [x] Private Packagist — ✅ 
- [x] Val Town — ✅ 
- [x] GitButler — ✅ 
- [ ] Rector — Not yet
- [x] Keygen — ✅ 
- [x] HTTP Toolkit — ✅ 
- [x] Chief Tools — ✅ 

I haven't collected the files in one place, because some branding materials include e.g. instructions on a webpage. For example, see <https://brandpad.io/astral>. Let me know if you do want all the files downloaded in one place.

**Comment by selviano** [comment]
awesome! It would be great if you could dump them in here: https://drive.google.com/drive/folders/1HxYaaY1wy1hZT6O0ZY58s7Y8N4aV0fcn?usp=sharing

This folder is publicly viewable as part of the greater Partner Kit, but I also gave edit access to your gmail. I’ll create placeholder subdirectories now!

**Comment by vladh** [comment]
@selviano Will do!

Rector are creating a new logo and will get that to us by Monday, hope that works.

**Comment by vladh** [comment]
@selviano I've uploaded all of the logos to the Google Drive folder.

**Comment by selviano** [comment]
thanks @vladh

**Comment by vladh** [comment]
Rector have provided us with a new logo which they've kindly made. I've added it to the Google Drive folder. I'm not sure whether it's too late to include. If we do include it, I don't think what we got will work on a dark background, so we'll have to make it white.

**Comment by selviano** [comment]
Thanks @vladh, I've sent to our design team. Closing this out now as we are going to send this off to NASDAQ at EOD
