### ISSUE TITLE
Use longer domain as canonical to reinforce correct name

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#120]
We continually see people using "OSS Pledge" as the name vs. "Open Source Pledge." Some of this confusion is likely unavoidable, but using the short domain as canonical surely doesn't help. Let's think about using the longer one as canonical.

### To Do

- [x] Move old `opensourcepledge.com` repo to `tmp-osspledge-redirect` with manual redirects. (@chadwhitacre)
- [x] Rename `osspledge.com` GitHub repo to `opensourcepledge.com` (@chadwhitacre)
- [x] Change domain in website files (@vladh) — #123 
- [x] Change domain in email draft (@vladh)
- [x] Set up osspledge.com → opensourcepledge.com redirect (@vladh + @chadwhitacre)
- [x] Set up val.town DNS for redirect (@chadwhitacre) — [instructions][redir]
- [x] Update Plausible (@chadwhitacre)
- [x] Update cal.com (@chadwhitacre)

[redir]: https://github.com/opensourcepledge/osspledge.com/issues/120#issuecomment-2363867693

**Comment by chadwhitacre** [comment]
e.g. https://github.com/opensourcepledge/osspledge.com/pull/111#issuecomment-2357909591

**Comment by mitsuhiko** [comment]
As part of the problem I'm obviously in favor :)

**Comment by vladh** [comment]
A lot of people are using “OSS Pledge”:

* https://github.com/opensourcepledge/osspledge.com/pull/111#issuecomment-2357909591
* https://github.com/opensourcepledge/osspledge.com/pull/116#issue-2533099367
* https://github.com/opensourcepledge/osspledge.com/pull/111#issuecomment-2357909591
* https://github.com/opensourcepledge/osspledge.com/pull/107#issue-2521030739
* https://github.com/opensourcepledge/osspledge.com/pull/72#pullrequestreview-2275843006
* https://github.com/opensourcepledge/osspledge.com/pull/69

I think using opensourcepledge.com is the best way to avoid confusion. Any potential cons? Longer to type?

**Comment by selviano** [comment]
We use osspledge.com on the billboards/ooh because the full opensourcepledge.com is too long for that format. But the OOH campaign is ephemeral and I think everywhere else we should use the full URL consistently

**Comment by chadwhitacre** [comment]
Okay! Let's do it.

**Comment by vladh** [comment]
Okay, here we go:

- [ ] Rename GitHub repo (@chadwhitacre)
- [ ] Change domain in website files (@vladh)
- [ ] Change domain in email draft (@vladh)
- [ ] Set up osspledge.com → opensourcepledge.com redirect (@chadwhitacre)

Anything else?

**Comment by mitsuhiko** [comment]
@vladh README and a few other places: https://github.com/search?q=repo%3Aopensourcepledge%2Fosspledge.com%20osspledge&type=code

**Comment by vladh** [comment]
Done in #123

**Comment by vladh** [comment]
@chadwhitacre When creating redirects, we'll have to do things differently than we have so far.

Currently, <opensourcepledge.com> redirects to <osspledge.com>. But <opensourcepledge.com/members> 404s instead of redirecting to <osspledge.com/members>.

So when changing the redirects now, we want to be sure that <osspledge.com/foo/bar> will redirect to <opensourcepledge.com/foo/bar> otherwise we'll have a lot of broken links.

**Comment by chadwhitacre** [comment]
Agreed. If we want to support a handful of existing URLs that's one thing, if we want to support all present and future URLs that another, need something dynamic or double-build or some such. We have another repo for the other domain atm.

**Comment by vladh** [comment]
FWIW, I'd point osspledge.com to an HTTP server that does an appropriate rewrite.

**Comment by vladh** [comment]
@chadwhitacre Neat idea! Here you go: https://www.val.town/v/vladh/opensourcepledgeRedirect

Example: https://vladh-opensourcepledgeredirect.web.val.run/foo/bar

**Comment by chadwhitacre** [comment]
Nice! @stevekrouse Any chance you want to donate a pro subscription to Pledge so we can set this up with our custom domain? 😬 🙇‍♂️ Then you could add that in `moneyValueOfMaterials`. 😌

**Comment by stevekrouse** [comment]
This is awesome! Thanks for thinking of us!

I'd love to help out - just checking with the team about the logistics of donating an account. We haven't done that yet and I'm not sure how it'd work in our database/stripe

**Comment by chadwhitacre** [comment]
Thanks @stevekrouse! If it's a pain I can just pay for it for now. 🙃

**Comment by stevekrouse** [comment]
Apparently it's very easy for us to toggle in our database, so just let me know the username of the account you want upgraded. Is it @vladh?

**Comment by vladh** [comment]
Thanks so much @stevekrouse! I'm happy to use my account for this, but maybe @chadwhitacre would like to do something else? Just checking.

**Comment by chadwhitacre** [comment]
Go for it @vladh. Thanks @stevekrouse!

**Comment by chadwhitacre** [comment]
If there's some sort of org or team account on val.town maybe we can use that? Otherwise I'm fine w/ vladh for now.

**Comment by stevekrouse** [comment]
Great! We don't have teams yet

**Comment by vladh** [comment]
Works! https://osp-redir-test.vlad.website/foo/bar

(This should redirect to https://opensourcepledge.com/foo/bar, which 404s.)

Thanks again @stevekrouse! 🙏🏻 

@chadwhitacre When you're ready, here's what needs to be set up for `osspledge.com.`:

```
@ CNAME domains.val.run.
www CNAME domains.val.run.
```

**Comment by chadwhitacre** [comment]
I need to run the DNS change through Sentry Ops, will do that next week. For now I've added manual redirects in the tmp-osspledge-redirect repo and flipped the switch in GitHub CNAME files.

**Comment by chadwhitacre** [comment]
Seems to be working?

https://osspledge.com/members/val-town

**Comment by vladh** [comment]
Oh wow, thanks for doing all that manually.

**Comment by vladh** [comment]
This 404s, FWIW: https://osspledge.com/osspledge.pdf

**Comment by chadwhitacre** [comment]
I mean, it wasn't _fully_ manual. ;-)

```python
import csv, os
members = csv.reader(open('../opensourcepledge.com/members.csv'))

for slug, url in members:
    fp = open(f'members/{slug}/index.html', 'w+')
    print(f'''
<meta http-equiv="refresh" content="0; URL='https://opensourcepledge.com/members/{slug}/'" />''', file=fp)
```

**Comment by chadwhitacre** [comment]
```
@ A 75.2.96.173
@ A 99.83.186.151
www A 75.2.96.173
www A 99.83.186.151
```

I made a [PR 🔒](https://github.com/getsentry/ops/pull/12178) to update the `A` records for the apex. `www` is `CNAME`d to the apex which should still be fine, yes?

**Comment by vladh** [comment]
Yep sounds good! 💃🏻

**Comment by chadwhitacre** [comment]
Plausible should be good: https://plausible.io/opensourcepledge.com.

**Comment by chadwhitacre** [comment]
DNS change deployed, wfm:

https://osspledge.com/random/path/redirects/to/opensourcepledge.com

I think we're done here?

**Comment by chadwhitacre** [comment]
Still waiting for propagation everywhere but seeing it some places. Closing!
