### ISSUE TITLE
Company Classification

### ISSUE THREAD

**Issue by dcramer** [opensourcepledge/opensourcepledge.com#126]
Right now we have a marketing problem that's fairly evident due to the way we've approached this leaderboard thing.

It doesn't do a good job of "selling" the pledge, because its just showing an assortment of primarily indie companies. Those companies we still want to be part of the program, but at the same time we have to recognize that a lot of the websites job is to market the pledge to aspirational companies.

I propose a few things to help address this (these are not all my ideas):

1. Remove the leaderboard. Make it a curated set of logos. As we get more recognizable brands, we adjust it.
2. Highlight new members (this is a good way to give folks recognition for joining, whether they're small or large). This might be highlight _everyone_ whos joined in the last N period.
3. $/dev is not a good metric (in general) and doesnt encourage big companies. While I applaud anyone giving $10k/dev, if someone comes in and gives $10mm total, vs someone elses $10k (for their only dev), we should recognize the value delta.
4. Find a way to classify indies/early stage in a way that makes them feel valued, but doesnt deemphasize from the reality that this primarily is successful from many larger companies joining. e.g. a company that stays at 3 developers is very different than a venture backed company that may be 3 today, 30 in a year, and 300 in 3 years. I'm not sure what terminology we should use here, but I think we should cleanly separate them into different categories, as we want the bigger/growth orgs to be the marketing/sell focus.

**Comment by vladh** [comment]
We could change the homepage to show:
* a curated list of companies/logos, to show credibility/impact, and
* the e.g. 3 most recent companies, to incentivise joining.

On the Members page, we could move towards a Company Explorer by having three columns: number of developers, total donated, $/dev (all for the last annual report). We could allow the user to sort by whatever column they want. Not sure what the default sort should be.

**Comment by chadwhitacre** [comment]
I think with the changes we made yesterday in #124 and #127 we've largely resolved these concerns wrt the /members listing. For the homepage it's easy enough to drop the $/dev column and just show logos, I agree with that (we talked about that somewhere, I forget if GH or private Slack, probably the latter).

> $/dev is not a good metric (in general)

Kinda late in the game to suggest this. What's the reasoning?

> and doesnt encourage big companies. While I applaud anyone giving $10k/dev, if someone comes in and gives $10mm total, vs someone elses $10k (for their only dev), we should recognize the value delta.

Sure, that doesn't mean it's not a good metric.

**Comment by chadwhitacre** [comment]
> a good metric

I think it's good but not enough, I think the direction we're going in #124 where we're moving /members more towards a data explorer is the right direction. $/dev is useful but needs to be looked at in context.

**Comment by chadwhitacre** [comment]
> Remove the leaderboard.

We have not had a leaderboard per se on the homepage since https://github.com/opensourcepledge/osspledge.com/pull/104 when we started sorting by ndevs desc. With #135 the homepage is brought into line with what we have on /members as low-hanging fruit.

> Make it a curated set of logos. As we get more recognizable brands, we adjust it.

The algorithm we have today is not bad. The largest company (by ndevs) is always shown, and each company after as a 50% chance of being shown on any given page load. I think this gives a good balance and naturally scales as we onboard larger and larger companies.

If we do want to change the presentation of member companies on the homepage even further, I'd like to bring in @stevenplewis.

**Comment by chadwhitacre** [comment]
Quick fix in https://github.com/opensourcepledge/opensourcepledge.com/pull/143 to get numbers off the homepage, we can work on better visual treatment separately.

**Comment by chadwhitacre** [comment]
@dcramer What is left to close this out?

**Comment by chadwhitacre** [comment]
1. **Remove the leaderboard.** - This is done, I think?
2. **Highlight new members** - Could do more here but everyone is new at this point. How high priority is this?
3. **$/dev is not a good metric** - I don't understand the ask here.
4. **Find a way to classify indies/early stage** - Is this still an issue given current state of homepage + /members?

**Comment by voxpelli** [comment]
> $/dev is not a good metric (in general) and doesnt encourage big companies. While I applaud anyone giving $10k/dev, if someone comes in and gives $10mm total, vs someone elses $10k (for their only dev), we should recognize the value delta.

Not sure about this one – why is it more expensive for a big company to donate $10k/dev than for a small one? If anything the big company is probably less impacted by it as they're not as reliant on a single person for their income and as such should have a more reliable income stream

Judging whether big or small companies have an easy or hard time to do what the other is doing feels like a guessing game this project should not indulge in.

**Comment by chadwhitacre** [comment]
Yeah I think we need to push back on this narrative that it's easier for smaller companies than larger to meet the minimum threshold. The whole point of $/dev is to abstract away from company size. Yes of course a larger company's minimum payment is larger in absolute terms but guess what—so is their revenue!

The main delta is in sales lead time, enterprise sales easily takes 18 to 24 months whereas a sole proprietor can buy on the spot. We should stay the course and trust the process, quite curious to see where we are at a year from now.

**Comment by chadwhitacre** [comment]
> **Remove the leaderboard.**

We got a bunch of monochrome wordmarks together for the Nasdaq Tower art, I'm expecting SVGs from Sentry's design team on Monday along with a mockup to replace the current homepage company listing with a different treatment based on those.

> **$/dev is not a good metric**

I don't understand the intent behind this and for the reasons in my previous comment I think $/dev is a great metric. Gonna ignore this until more direction is forthcoming.

> **Highlight new members**
> **Find a way to classify indies/early stage**

I believe these both have the same intent and I think our existing algorithm does a good enough job of addressing: we always show the largest company, and then each after that has a 50% chance of being shown on the homepage.

**Comment by vladh** [comment]
> We got a bunch of monochrome wordmarks together for the Nasdaq Tower art, I'm expecting SVGs from Sentry's design team on Monday along with a mockup to replace the current homepage company listing with a different treatment based on those.

On a logistical note, I'll make sure I'm free through Tuesday so that I am able to implement these changes at short notice.

**Comment by chadwhitacre** [comment]
Here [a zip of monochrome wordmarks for most current members](https://github.com/user-attachments/files/17283223/wordmarks.zip). Let's use a similar treatment as on [Sentry's homepage](https://sentry.io/welcome/), but with 5 across instead of 6 at max width, and a configurable number of rows (we'll start with one or two).

<img width="1157" alt="image" src="https://github.com/user-attachments/assets/2df5e6f5-ddca-4caa-ae87-fa61c5d0ecd6">

Unfortunately the code is closed-source. I've extracted hopefully [enough in this gist](https://gist.github.com/chadwhitacre/4904208c467bc360c392f0657e33312d) to point in the right direction. Note in particular that the logo sizes are adjusted using the `maxHeight` property in order to make them look good next to each other visually.

**Comment by vladh** [comment]
@chadwhitacre For what it's worth, there's a bug in that code on sentry.io.

This:

```
<SocialProofLogoCell key={logo} xs={xs} sm={sm} md={md} lg={lg}>
  <LogoDescriptor id={`logo-${logoName}`}>${logoName} logo</LogoDescriptor>
  <StyledLogo as={logo} maxHeight={maxHeight} aria-labelledby={`logo-${logoName}`} />
</SocialProofLogoCell>
```

Yields

```
<div class="css-1jiv55k e66bsfo1">
  <title id="logo-Atlassian" class="css-1lbs7b e66bsfo2">$r logo</title>
  <svg aria-labelledby="logo-Atlassian" ...>...</svg>
</div>
```

But:

* `<title>` is not valid there. It is valid inside `<svg>`, perhaps it was supposed to be there?
* `${logoName} logo` yields `$r logo`, for all the logos. For one thing, there shouldn't be a `$` there. But also, `{logoName}` is coming out as `r` for all logos for some reason.

**Comment by vladh** [comment]
Logos done in #177.

**Comment by chadwhitacre** [comment]
Calling this good with #177. Please reticket additional tactical changes if necessary.
