### ISSUE TITLE
Deemphasize Sentry

### ISSUE THREAD

**Issue by dcramer** [opensourcepledge/opensourcepledge.com#129]
There's two goals we have:

- Recognition for people that put in resources/effort to make this thing work (Sentry obviously started this)
- Don't confuse people that "this is Sentry"

What this looks like might be focusing on some of our larger founding members, or just moving the notes about Sentry to the "Who runs the Pledge?" (where we have the contributors here recognized already)

**Comment by dcramer** [comment]
Also this is somewhat minor, I just don't want people to have excuses that "this is Sentrys marketing campaign". It is, but its also not. We're spending a lot of time and money because its valuable, but its not like some trick to get free advertising for Sentry either. We recognize the value of thought leadership in brand recognition (which is how we deem ROI on these investments), and we want others to recognize that too ("make it your own"). I dont know how we best walk this line, but probably some minimal changes.

**Comment by vladh** [comment]
Regarding mentions of Sentry, we could do this: #130 

Regarding focusing on other larger founding members, we can figure that out as part of #126 

My opinion FWIW: whatever the details of Sentry's ROI motivations, this initiative _is_ getting money to underpaid maintainers, and that's Good, and that's what matters.

**Comment by vladh** [comment]
I think we’ve resolved this. Happy to reopen if not.
