### ISSUE TITLE
Rename to Open Source Pledge

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/opensourcepledge.com#14]
We're changing names from “OSS Pledge” to “Open Source Pledge”, and URLs from https://osspledge.com to <https://opensourcepledge.com>.

- [x] Change name in repo — #15 
- [x] Acquire new domain
- [x] Migrate to new domain
- [x] Change URL in repo (blocked on new domain) — #17
- [x] Change repo name (will redirect)
- [x] Change organisation name (will redirect)
- [ ] Look through GitHub issues to catch any dangling references to osspledge.com
- [x] Update at Plausible

**Comment by vladh** [comment]
Random small thing — I'm abbreviating Open Source Pledge as `osp` in identifiers, as opposed to `ossp`.

**Comment by chadwhitacre** [comment]
Agreed on `osp` as abbreviation.

I've change the org and repo names, redirects seem to be fine. I've created a `legacy-already` repo for redirecting https://osspledge.com/.

**Comment by chadwhitacre** [comment]
https://plausible.io/osspledge.com
↳ https://plausible.io/opensourcepledge.com

**Comment by chadwhitacre** [comment]
I looked through open GH issues and made some updates. Calling this good!
