### ISSUE TITLE
Update About page with more FAQs

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/opensourcepledge.com#150]
This should include things like a more detailed breakdown of which payments count towards the Pledge and which not, details on why, as well as the fact that we're still considering issues like purchasing power parity, links to respective issues, and so on.

**Comment by chadwhitacre** [comment]
I mean we have a FAQ sort of already? Could certainly be improved. Or is this a separate page?

**Comment by vladh** [comment]
Yep — rephrased it!
