### ISSUE TITLE
Show badge on member profile

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#156]
We should show the "Open Source Pledge Member" badge on member profiles.

For those who join before Oct 8 the badge variant should be "Open Source Pledge Innovator."

**Comment by chadwhitacre** [comment]
Mock from @stevenplewis solving the problem with a tag vs. badge:

![image](https://github.com/user-attachments/assets/f09a9059-a503-469f-a290-e8c29804c609)

**Comment by vladh** [comment]
Looks beautiful, will get this done tomorrow. Do we want different colours for one badge vs the other?

**Comment by chadwhitacre** [comment]
Probably? Not sure what all badges we'll have yet. Ecosystems might be nice? Could tie in with foundation membership? Perl, PHP, Python, etc.
