### ISSUE TITLE
Nonexistent (expired?) link in the README

### ISSUE THREAD

**Issue by Julian** [opensourcepledge/opensourcepledge.com#158]
The "upcoming ecosystem call link" in the [README](https://github.com/opensourcepledge/opensourcepledge.com?tab=readme-ov-file#open-source-pledge) is a 404 (which leads to https://cal.com/osspledge/ecosystem-call).

I saw https://github.com/opensourcepledge/opensourcepledge.com/issues/37#issuecomment-2334465458 says a call happened already, so perhaps the link is simply expired and was for that one?

Happy to send a PR of course either removing the link or updating it as well, though I bet whoever knows the answer to what should happen could do it faster than me doing so.

(Would love to know if there are plans to have an ongoing call as well. Props again for all you're doing!)

**Comment by Delta456** [comment]
Yes, the call already happened. We should update it whenever the next one is scheduled as https://github.com/opensourcepledge/opensourcepledge.com/issues/11 says.

We used to have weekly calls on Discord but it has been paused because of lack of participation.

**Comment by vladh** [comment]
Oops, thanks for letting us know @Julian!

I've made a quick fix for now — we'll likely expand the instructions after the launch.
