### ISSUE TITLE
Onboard Platformatic

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#182]
Picking up from #180, we choked on their json in https://github.com/opensourcepledge/opensourcepledge.com/actions/runs/11235710752/job/31234231140.

**Comment by chadwhitacre** [comment]
b04740bf5458b407d3a0ea3a6ea5b0df5fb2ed2f 🤞

**Comment by vladh** [comment]
LGTM, thank you!
