### ISSUE TITLE
Publish the partner kit as a Resources page

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#196]
Now that we're live let's make it easier for [people like this](https://x.com/carlos_granados/status/1844382610509922343) to self-serve by putting up a page at /resources that has the content from the [partner kit](https://drive.google.com/drive/folders/1W5-Jc4pjcCa1mk9UuyKlauwvuUeuwxxU).

[Jira ticket🔒](https://getsentry.atlassian.net/servicedesk/customer/portal/17/DTSD-1331) for design.

**Comment by thevishvammoliya** [comment]
I would love to work on this feat., can you elaborate on specific design requirements?

**Comment by vladh** [comment]
Hi @thevishvammoliya! Thanks for offering to help. I think someone on the Sentry design team is already handling the design here.

**Comment by thevishvammoliya** [comment]
@vladh not a problem, always open to contribute, feel free to tag me

**Comment by chadwhitacre** [comment]
Here's the mock, @0xvish. Does that give you enough to get started?

![oss-promo-kit-pg](https://github.com/user-attachments/assets/51618a2e-f115-46b1-8a57-90883dfef453)

**Comment by chadwhitacre** [comment]
Mock will take some tweaking. Title should be "Resources" e.g.

**Comment by vladh** [comment]
Assigning to @0xvish assuming they're able to do it, I'm happy to do it otherwise.

**Comment by 0xvish** [comment]
Hello @vladh, thanks for considering me! I'm on holiday but can start on this from Wednesday, Nov 6th. Apologies for any delay—please feel free to reassign if needed, though I'd be happy to handle it after the 6th. Thanks!

**Comment by vladh** [comment]
Should be fine! :)

**Comment by 0xvish** [comment]
Hey, /resources route already exists and it has the page with downloadable assets like images.

Any specific requirements for the route of the partner-kit page?

**Comment by vladh** [comment]
@0xvish I think we should probably merge the two pages into one, ie add the stickers to the above mock-up. 🤔

**Comment by 0xvish** [comment]
Alright, adding above content to the Resource page, keeping the existing content as it is, will commit with the changes, then let me know if any canges are needed.

**Comment by vladh** [comment]
Partially resolved in #247 — still have to make this page visible etc. I’ll handle that soon.
