### ISSUE TITLE
List press coverage somewhere

### ISSUE THREAD

**Issue by colindean** [opensourcepledge/opensourcepledge.com#202]
I noticed [this Technical.ly story](https://technical.ly/software-development/open-source-pledge-developer-pay/ "How open-source software devs got corporations to pledge $1.3M for their tools") coming up in my news feeds and thought about how it'd be a good idea to have a press coverage list so people can read articles written about the project.

It could probably start as just an entry on the About page and maybe graduate to its own page after it hits some arbitrary size.

**Comment by vladh** [comment]
Thanks for thinking of this @colindean! I think we can probably integrate this into the [Endorsements][endorsements] page. I wonder if we should make that page easier to find — I wonder if it was obvious to you, @colindean.

[endorsements]: https://opensourcepledge.com/endorsements/

**Comment by colindean** [comment]
I spotted it when I was looking around for an existing press page. I wouldn't put them on the same page without renaming it something like "endorsements and press coverage." For my organizations, I've sometimes used, "nice things people say about us," and then just slapped a press subheader in there somewhere.

**Comment by vladh** [comment]
Gotcha! I'll wait until we have a bit more press coverage then do something about this. Thanks for the help! :)

**Comment by colindean** [comment]
Sounds great. Big fan here and trying to make some moves in the orgs in which I have influence.

**Comment by chadwhitacre** [comment]
@selviano Can you dump links here to give us some material to work with?

**Comment by selviano** [comment]
Here are some links. There are some additional ones that are more "forums" than articles, but I think we should stick to actual articles

- https://changelog.com/news/112
- https://technical.ly/software-development/open-source-pledge-developer-pay/
- https://www.developer-tech.com/news/open-source-pledge-fund-software-maintainers/
- https://www.youtube.com/watch?v=_3SVKdgpaH8
- https://www.infoworld.com/article/3557846/how-do-we-fund-open-source.html
- https://sf.gazetteer.co/wild-billboards-around-the-bay-call-attention-to-tech-companies-free-loading-off-open-source-projects?giftLink=e7b31c342349daae329c6196cdd680e2
- https://www.theregister.com/2024/10/25/open_source_funding_ads/

**Comment by chadwhitacre** [comment]
Great to have this page, kinda funny that Theo is press. 😜

@selviano Let us know when we have more to add. Maybe the [MSN](https://www.msn.com/en-us/money/other/san-francisco-billboards-call-out-tech-firms-for-not-paying-for-open-source/ar-AA1sVKkC) syndication?
