### ISSUE TITLE
Incorporate monochrome wordmark collection into onboarding

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#207]
With the new monochrome wordmarks on the homepage we have a split in how we're onboarding. We should really collect those from every company when they join, but the JSON is not set up for that, so we're collecting out of band. We could leave this as-is, or add this to the JSON, or reduce what we take from the JSON vs. directly through GitHub PRs or whatever.

**Comment by vladh** [comment]
Related to #189.
