### ISSUE TITLE
Make stickers

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/opensourcepledge.com#210]
Idea from [@zeeg's tweet](https://x.com/zeeg/status/1844392377026564166).

Related to #196.

Events such as FOSDEM are slowly coming up, and it would be great to get the assets done for stickers ahead of time. I can have some printed locally and bring them to FOSDEM.

Would it make sense to send our members a physical “care pack” of stickers etc.? cc @chadwhitacre

**Comment by dcramer** [comment]
Got some stuff in the works 👀

**Comment by Ethan-Arrowood** [comment]
I'll be speaking at NodeConfEU in early november. I'd love to bring some stickers, but will need them delivered to my home before October 27th (when I leave for Ireland). Otherwise, we could try to ship to the conf venue or something 🤷‍♂️

**Comment by dcramer** [comment]
> I'll be speaking at NodeConfEU in early november. I'd love to bring some stickers, but will need them delivered to my home before October 27th (when I leave for Ireland). Otherwise, we could try to ship to the conf venue or something 🤷‍♂️

Let me see what timing looks like. Working on getting some stuff printed but timing might be tight. If we get them here in time I can ship some your way, otherwise maybe we can stickermule or something similar a quick pass.

**Comment by vladh** [comment]
Happy to get the files printed here in the UK if that helps.

**Comment by Ethan-Arrowood** [comment]
Yeah let me know! I can send shipping address info via email whenever

**Comment by dcramer** [comment]
Will circle offline, but 

1) we’ll publish the assets we’ll use for these somewhere in here (in the spirit of this being a community effort)
2) sentry will fund the cost of some of this (and in this situation we can figure out how to get some for both of these events above)

**Comment by chadwhitacre** [comment]
PR in https://github.com/opensourcepledge/opensourcepledge.com/pull/222 has sticker files (in a stubbed-out Resources page).

@vladh @Ethan-Arrowood We can either buy them if you give us the details or you can and we'll send money if under $500, just need a receipt.

**Comment by vladh** [comment]
I’ll get some printed and keep you updated! 🎉

**Comment by dcramer** [comment]
FYI to avoid art issues we’re gonna during out asset licensing. Mostly we want to ensure that the assets are only used to represent the pledge (vs someone yoink it for their own website. Means they might not be CC. Either way for now we approving permission to print these as stickers to represent the pledge.

**Comment by Ethan-Arrowood** [comment]
Just submitted an order for the two images in that pr. I'll email a receipt as soon as the order gets confirmed.

**Comment by dcramer** [comment]
Opened https://github.com/opensourcepledge/opensourcepledge.com/issues/223 to figure out the creative concerns

**Comment by Ethan-Arrowood** [comment]
![image](https://github.com/user-attachments/assets/79edb296-1a3e-40b6-9379-d66906c460d1)

Stickers are here! They look great

**Comment by vladh** [comment]
Amazing! Mine are on their way too. :)

**Comment by vladh** [comment]
![stickers](https://github.com/user-attachments/assets/ec6ac297-2a37-4299-b264-e76bbefa17f4)

Got my stickers and they look amazing!

I think we can close this now.

**Comment by chadwhitacre** [comment]
https://x.com/chadwhitacre_/status/1851254372497326268
https://x.com/chadwhitacre_/status/1851071347021021399
https://x.com/darcy/status/1851059518769148284

**Comment by vladh** [comment]
https://fosstodon.org/@opensourcepledge/113402768467383307
