### ISSUE TITLE
Determine license for creative assets

### ISSUE THREAD

**Issue by dcramer** [opensourcepledge/opensourcepledge.com#223]
We want to contribute assets to the Open Source Pledge and have those be usable in a variety of purposes, very similar to trademark purposes. Normally we'd just donate things under an open source license, but with media its actually more tricky than that. One example of what we want to avoid is someone taking the assets, uploading them to stockphoto, and trying to sell them. We also want to avoid people taking the assets and using them to represent something that is _not_ the pledge. I'm not familiar w/ media licensing so don't have any particular idea here, but it might be we just retain full IP and give a list of allowed purposes, in which we will implicitly grant a license.

**Comment by vladh** [comment]
I think a simple solution might be to trademark both the word mark (“Open Source Pledge”) and the figurative mark (the logo), and then to allow these to be used only when adhering to trademark guidelines:

* https://opensource.org/trademark-guidelines
* https://opensource.org/logo-usage-guidelines#Logo_Usage

My understanding is that, in this situation, the logo is not permissively licensed, and one good reason for that seems to be preventing derivatives, which I think makes sense for a logo.

**Comment by Delta456** [comment]
I mostly agree with @vladh here. 

>  we want to avoid is someone taking the assets, uploading them to stockphoto, and trying to sell them

I feel that should be fine because not everyone can purchase at the same disparity in terms of purchasing. 


I think the Go Brand Guidelines make this clear

> Swag should never be advertised as “official” swag or swag endorsed for use or purchase by the Go programming language project.

> There are no other restrictions on generating revenue through swag that use the Go Trademarks. However, we encourage sellers to consider the ethos of the open source movement in this decision. Sellers must truthfully advertise to consumers how much of the selling price, if any, will be donated to open source or community efforts.

There are many more points in https://go.dev/brand which can help to learn how we can go forward with this.

**Comment by ShaneCurcuru** [comment]
Are these assets specifically for/about the "Open Source Pledge", or are they more complex images that might have associations with Sentry or some other company/product?

Question: would a CC-BY-NC or similar type license meet the needs for media like this?  At least that way everything in the project would be under well-understood license terms, and not some custom agreement that's opaque to others.

If there's concern the "Open Source Pledge" term will be misused in general, that's the first question to address in terms of this project, and is mostly in terms of trademarks.

A related question is about governance and licensing of the project overall: is the true intent to have a multi-stakeholder governance, and treat the work of the pledge as a community-led open source project for the long haul?  Just curious: any way to govern is fine, as long as it's well documented and clear to readers.

**Comment by vladh** [comment]
> Are these assets specifically for/about the "Open Source Pledge", or are they more complex images that might have associations with Sentry or some other company/product?

The former.

> Question: would a CC-BY-NC or similar type license meet the needs for media like this? At least that way everything in the project would be under well-understood license terms, and not some custom agreement that's opaque to others.

I see the merits there, I think the concerns were (1) attribution seems difficult for stickers, and (2) I don't think people selling stickers is a problem (especially if the revenue is paid to maintainers).

> A related question is about governance and licensing of the project overall: is the true intent to have a multi-stakeholder governance, and treat the work of the pledge as a community-led open source project for the long haul? Just curious: any way to govern is fine, as long as it's well documented and clear to readers.

Great point, I think we need to address this more.
