### ISSUE TITLE
Budget through Jan 31

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#226]
Sentry has approved an allocation of $60,000 to support building the Pledge through January 31, 2025 (the end of our fiscal year). This includes stickers (#210) and whatever else we want to prioritize, especially ofc compensating community members such as @vladh @Ethan-Arrowood et al. for their contributions.

This issue is for putting together a plan for how we want to allocate these funds, and also putting in place accounting logistics.

**Comment by vladh** [comment]
Thanks @chadwhitacre, I'm very grateful to Sentry for this budget.

As far as costs for my own work, here's how I would normally do this. I can track my time spent on Pledge-related work, organised by task, and submit regular itemised invoices to Sentry. I'm happy to make this publicly transparent, too. Let me know if this works for Sentry, and if so, I can get started.

More generally, we could earmark parts of the budget for certain uses. Are there significant advertising expenses right now, for example? I can't think of any big non-labour costs off the top of my head, but we can also earmark things as we go along.

**Comment by chadwhitacre** [comment]
> submit regular itemised invoices to Sentry

My ideal would be for us, with this 60k budget, to start thinking of it as the Pledge's balance and not Sentry's (even if for the time being Sentry is the fiscal host for the Pledge). If successful we will likely spin up a separate entity for the Pledge, let's start skating ahead of that puck.

> non-labour costs

The only one I'm aware of so far is stickers. 🙃 It might be good to reserve 5% or 10% of our budget for other things that might crop up like this. Wdyt?

Otherwise you're right, we should mostly budget for labor. Personally I don't think we need super-detailed invoices, I think a weekly invoice for a single line-item number of hours would be fine. I would like to create the possibility for others to participate such as @safwanyp (see #220), @Delta456, and @dmk246 (whom I've been talking with about helping us with data entry in our CRM). The main task as I see it is to establish our practice for setting compensation amongst ourselves in a way that fits the Open Source character of the community we're trying to build around the Pledge itself. Based on [my past experience with take-what-you-want compensation](https://gratipay.news/sharing-our-take-what-you-want-story-911dad62ac32), I would like to try something in that vein here as well.

I propose that we start a public `finances` repo that has a CSV with columns `GitHub username` and `hourly rate`. This will provide transparency into who is taking compensation at what rate. Our rule should be that Pledge admins can add or remove members from this list, but only the person themselves can change their rate (if someone is not comfortable with pull requests it would be enough for them to state their rate in a public issue). Then, team members would submit invoices via GitHub issues on some cadence (weekly?), and we could track financial transactions in the repo as well (possibly using [beancount](https://beancount.github.io/)?).

What do you think? :)

**Comment by vladh** [comment]
@chadwhitacre Agreed, let's do this! I'll get this started.

My only comment is on the granularity of the invoices. I see the point about making things low-friction. But I think it might be helpful to have invoices have one line item per general task. This is so that we can see what we spent money on down the road, so that we have the option to re-prioritise. If we end up going over budget, for example, it's useful to be able to go back and say “hmm, we put a lot of work towards X, which is not the most important, but cost us a lot of money”. What do you think?

**Comment by chadwhitacre** [comment]
Well, since you're the one it affects the most, I'm fine with the additional level of detail. :o)

We could even do similar to the CRM repo where we have semi-structure issue descriptions, so a team member would create an issue like:

```
- 10 - work on something
- 2 - work on something else
- $199 - stickers
```

And we could automatically generate a PDF invoice from that, using their hourly rate from the CSV. Thoughts?

**Comment by vladh** [comment]
Hmm, not sure how automatic invoice generation would work, because everyone will have to generate invoices differently depending on their situation, country of incorporation, mode of incorporation and so on.

But let's stick with the issues idea, I'll get something started now.

**Comment by vladh** [comment]
Done! https://github.com/opensourcepledge/finances

@chadwhitacre It would be great if you could check my work since I am a beancount beginner. 👉🏻 👈🏻

**Comment by vladh** [comment]
I think we should be explicit about what granularity we expect for time tracking, if any. I really don't know, here are all the options I can think of:

* Full granularity, eg use a timer where possible (sometimes it's not possible)
* Round to 6 minute increments, so to 0.1 hours (the doctor/lawyer approach)
* Round to 15 minutes increments
* Round to hour increments
* We don't care

**Comment by chadwhitacre** [comment]
I'm from 15 to we don't care.

**Comment by vladh** [comment]
I'm going to invoice every Monday, since I often do work at the weekend.

**Comment by safwanyp** [comment]
This is just my curiosity. Not trying to imply anything.

I'm just wondering if me or anyone else, as a contributor to opensourcepledge's stuff can create an invoice as well? Will this be something you guys plan to start working towards? The reason I ask is simply because I have been trying to get into open source for a while, and the pledge is an amazing initiative. I'm just trying to understand how things work around here 😅

**Comment by vladh** [comment]
@safwanyp Yes! We'd love to compensate contributors for their time. We're still working out the details, but see here: https://github.com/opensourcepledge/opensourcepledge.com/issues/226

**Comment by safwanyp** [comment]
@vladh I assume you mean to link Chad's comment, but yes okay that makes sense! Thanks a lot for everything you guys are doing

**Comment by vladh** [comment]
Just meant to link to that whole funding issue where we're working out the details of funding.

**Comment by chadwhitacre** [comment]
> see here: https://github.com/opensourcepledge/opensourcepledge.com/issues/226

Haha circular reference 🙃

@safwanyp you are breaking new ground as our first new contributor. If you would like to help us experiment with this new process, the thing to do is for you to make a pull request to [the `team.csv` file in the finances repo](https://github.com/opensourcepledge/finances/blob/main/team.csv), adding your GitHub username and your hourly rate (USD). I think if you also let us know how many hours you would expect to bill for #220 then we would be able to have an informed conversation before merging your team.csv PR. Sound good? :)

**Comment by vladh** [comment]
Lol we were on that issue already 🤦🏻‍♂️

**Comment by safwanyp** [comment]
@chadwhitacre Sounds perfect 😁 I've opened a PR with my usual hourly rate. Since it's in the Swedish currency, I just used the SEK -> USD converted number. I've added my billable hours as well. 

https://github.com/opensourcepledge/finances/pull/3

**Comment by safwanyp** [comment]
> > what granularity we expect for time tracking
> 
> Let's go with 15-minute increments. Agreed @vladh @safwanyp?

Yes absolutely! 15 mins works perfectly for me, and i think it gives a nice bit of leeway for any other contributors too!

**Comment by chadwhitacre** [comment]
I'm experimenting with tracking hours in a [timesheet issue](https://github.com/opensourcepledge/finances/issues/4), thinking one a week (though since I'm paid by Sentry I won't actually invoice).

**Comment by safwanyp** [comment]
Looks interesting! Do you plan on storing these timesheets somewhere? I'm sure we could easily setup an automation to parse these issues and persist the records.

**Comment by vladh** [comment]
> Let's go with 15-minute increments. Agreed @vladh @safwanyp?

Yes, I think that works great.

> I'm experimenting with tracking hours in a [timesheet issue](https://github.com/opensourcepledge/finances/issues/4), thinking one a week (though since I'm paid by Sentry I won't actually invoice).

Cool! I'll submit all of my hours as part of each Monday invoice.

**Comment by chadwhitacre** [comment]
> Do you plan on storing these timesheets somewhere?

Yes: in GitHub issues. 😬 😁 💃 

> I'm sure we could easily setup an automation to parse these issues and persist the records.

Maybe if it becomes worth it. I might also track locally vs. in issues, just experimenting right now. 🙃

**Comment by vladh** [comment]
Just throwing it out there: we need to decide/document who will update `accounts.beancount` when. 🤔

**Comment by vladh** [comment]
Sorry, just realised — @chadwhitacre has to be the one to update `accounts.beancount`, because he will be the only one who sees all submitted invoices.

Updated invoice submission instructions here: https://github.com/opensourcepledge/finances?tab=readme-ov-file#submitting-expenses

**Comment by chadwhitacre** [comment]
I think it might be easier to not use beancount, but rather just depend on whatever Sentry is using and share out reports periodically from there. I am working with our AP person to set up the accounting on our side, I'll follow up when that's further along.
