### ISSUE TITLE
invite Vercel to join Open Source Pledge

### ISSUE THREAD

**Issue by Delta456** [opensourcepledge/opensourcepledge.com#229]
I saw Vercel sponsoring a lot of open source developers a one-time 2K USD through GitHub Sponsors and Open Collective which fits the first requirement to join the Pledge as [stated](https://opensourcepledge.com/join/). 

I would like to invite them to join the Pledge as it can help us even more transition and potentially more companies will join the Pledge. 

Tweet and other things related to this: https://x.com/MelkeyDev/status/1850931780834283604

If everyone agrees then we can write a formal invitation to Vercel! :rocket:

**Comment by vladh** [comment]
Already working on this! 🔥
