### ISSUE TITLE
Auto-detect 404 reports

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#235]
From @selviano in https://github.com/opensourcepledge/crm/issues/69:

> We should consider a way to audit member posts and automatically detect 404s, as it will only get harder to track these as we scale...

**Comment by vladh** [comment]
On it!

**Comment by vladh** [comment]
Done in #240.

I've run it already: https://github.com/opensourcepledge/opensourcepledge.com/issues

**Comment by chadwhitacre** [comment]
Nice! What if instead of creating new issues in here we were able to post comments on the relevant CRM issue?

**Comment by chadwhitacre** [comment]
I guess that can be a new ticket.

**Comment by chadwhitacre** [comment]
→ #241
