### ISSUE TITLE
Do away with remote hosted JSON

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#242]
Is the remote hosted JSON [more trouble than it's worth](https://github.com/opensourcepledge/opensourcepledge.com/pull/240#discussion_r1825911549)? Time to do away with it? Likely makes onboarding simpler since we're already doing more manually now.

**Comment by chadwhitacre** [comment]
It seems that renewals are going to be more manual than not, which means we basically don't have much incentive to maintain a fully automated system at this point. I think we do away with this to make onboarding easier.

**Comment by vladh** [comment]
I’ll put together a proposal for this soon. (Am feeling better :)
