### ISSUE TITLE
Speakeasy: ‘learn more’ URL not found

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/opensourcepledge.com#243]
Speakeasy's `urlLearnMore` could not be retrieved. Please check the following URL: https://www.speakeasy.com/post/oss-pledge-2024.

**Comment by safwanyp** [comment]
Seems like a change in the slug that wasn't updated to you guys? 
https://www.speakeasy.com/post/open-source-pledge-2024

**Comment by vladh** [comment]
Yeah — I’ve contacted them.

**Comment by vladh** [comment]
Fixed by Speakeasy and also superseded by #254.
