### ISSUE TITLE
Add Bluesky link to website

### ISSUE THREAD

**Issue by selviano** [opensourcepledge/opensourcepledge.com#250]
We should also add our Mastodon, but here's a cool asset we can add for Bs: https://bsky.app/profile/philhawksworth.dev/post/3labrybt5lb23

**Comment by chadwhitacre** [comment]
Already added in https://github.com/opensourcepledge/opensourcepledge.com/pull/248, though w/o the nifty effect. :)

**Comment by vladh** [comment]
Done and looking cute, check it out in the footer: https://opensourcepledge.com

**Comment by chadwhitacre** [comment]
😍
