### ISSUE TITLE
Submit to FOSS Backstage 2025

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/opensourcepledge.com#251]
https://25.foss-backstage.de/

**Comment by vladh** [comment]
I've prepared a proposal: https://program.foss-backstage.de/fossback25/talk/review/EPTH9JDYXUSYSTTHRQ3PANXXL8HEJ9YS

It's mostly the same as the FOSDEM one. @chadwhitacre @selviano and others, let me know if you have any feedback.

@chadwhitacre I've added you as a speaker, let me know if you can't make it.

Unless anyone has objections, I'll submit next week.

**Comment by vladh** [comment]
Will submit this tomorrow.

**Comment by vladh** [comment]
![2024-11-13-20-01-42](https://github.com/user-attachments/assets/34d684e7-8f68-4d1d-9097-4152e9c90741)

Still reviewable here: https://program.foss-backstage.de/fossback25/talk/review/EPTH9JDYXUSYSTTHRQ3PANXXL8HEJ9YS

**Comment by chadwhitacre** [comment]
Oh well. Thanks for trying.
