### ISSUE TITLE
Sanity joins the Open Source Pledge

### ISSUE THREAD

**Issue by kmelve** [opensourcepledge/opensourcepledge.com#263]
We're excited to join the Open Source pledge!

## The pledge

For 2024, we're pledging $112,000 for our 56 FTE engineers.

## A link to our blog post.

https://www.sanity.io/blog/sanity-joins-the-open-source-pledge

## A short (less than 600 character) description of our company, including why we're joining.

Sanity is the content operating system that lets teams structure content and deliver it through APIs to digital products. We're joining the Open Source Pledge because we believe in supporting the open source projects and maintainers that our platform is built on. As a company, we have the privilege of using and benefiting from many open source libraries, frameworks and tools. By committing to give back financially to the open source ecosystem, we hope to play a small part in making open source more sustainable.

## Our branding materials.

Here are SVGs for our word mark and logo.

![sanity-logotype--red-on-white](https://github.com/user-attachments/assets/9c86d998-d6ca-47fb-bc16-7c9218e1a1f9)
![sanity-logotype--red-on-white-1](https://github.com/user-attachments/assets/34d03147-0114-40ab-8db4-4051a08a5577)
![sanity-monogram--red-circle](https://github.com/user-attachments/assets/46a0f152-4520-4d01-96b5-970bc237237d)
![sanity-monogram--white-on-red](https://github.com/user-attachments/assets/5ba2f881-2c87-47aa-b454-1adb84fa6fc2)

**Comment by vladh** [comment]
You should be good to go in #267. 🎉 

Just waiting for a second review.

**Comment by chadwhitacre** [comment]
Woo-hoo! Welcome aboard! 🎉
