### ISSUE TITLE
Consider adding a LinkedIn presence

### ISSUE THREAD

**Issue by vladh** [opensourcepledge/opensourcepledge.com#268]
Requested by @kmelve.

I think this one is a bit tricky because we need someone who (1) is free to manage this, and (2) is confident in speaking to decision makers/CEOs.

**Comment by chadwhitacre** [comment]
I reserved a page for us at https://www.linkedin.com/company/105794859/.

**Comment by Delta456** [comment]
I want to volunteer for this.

**Comment by chadwhitacre** [comment]
Thanks @Delta456. @selviano and @gregkumparak are taking the lead on this, to keep it consistent across all of our social media accounts.
