### ISSUE TITLE
Zerodha joins the Open Source Pledge

### ISSUE THREAD

**Issue by vishnus** [opensourcepledge/opensourcepledge.com#272]
Hi there,

We, [Zerodha](https://zerodha.com), would like to join the Open Source Pledge. 

**A link to your blog post:** https://floss.fund/blog/open-source-pledge-2024/

**A short (less than 600 character) description of your company, including why you're joining:**
At [Zerodha](https://zerodha.com/), we have always been passionate about contributing to a sustainable ecosystem for Free (libre) and Open Source Software (FOSS). As one of India's largest stock brokers, our journey has been deeply intertwined with FOSS, which has been instrumental in our growth. We've relied on FOSS technologies to build and scale our products, business, and services. By joining the Open Source Pledge and sharing our journey, we hope to inspire other companies to take similar steps. Supporting the open source projects we rely on is not just a responsibility; it's an opportunity to contribute to a sustainable and innovative future for the tech industry.

**Your branding materials:**
![zerodha-icon-whitebg](https://github.com/user-attachments/assets/8e4d4f3e-35da-4fb6-84b7-1c7575932573)

![zerodha-icon-transparent](https://github.com/user-attachments/assets/6895bfbe-35d5-4150-b641-6d6210aabe98)

![zerodha-logo-transparent](https://github.com/user-attachments/assets/262b0735-42eb-4eeb-8262-104b75062444)

**Comment by Delta456** [comment]
This is awesome :rocket:

**Comment by vladh** [comment]
@vishnus So nice and exciting to have you guys on board, your leadership in FOSS funding is amazing! 🎉 

I'll get you on-boarded right now, will follow up with an update.

**Comment by vladh** [comment]
Done in #273, waiting for a second review then we're ready to get this live. 🎈

**Comment by vladh** [comment]
Socials:
* https://fosstodon.org/@opensourcepledge/113509662160712707
* https://bsky.app/profile/opensourcepledge.com/post/3lbchfflaus2u

**Comment by chadwhitacre** [comment]
Yay! Welcome aboard! 😍
