### ISSUE TITLE
Set up and/or document preview builds for blog posts

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#293]
https://www.sanity.io/docs/preview-content-on-site

Incidentally, I clicked "publish" with a future publish date and rebuilt the site in GH and my content showed up on the blog oops! 🐭

**Comment by vladh** [comment]
D'oh, I know what it is, sorry, fixing right now.

**Comment by chadwhitacre** [comment]
Oh I see! It's in the listing but the page itself is 404.

**Comment by vladh** [comment]
If only I had implemented checks in both places! 🙃

**Comment by vladh** [comment]
Fixed on main, deployed.

**Comment by chadwhitacre** [comment]
Would it work to build pages always but not include surface them in a) the listing b) RSS c) search engines prior to publish date? That would address my use case on this ticket, ya?

**Comment by vladh** [comment]
Yep. (a) is trivially done. (2), we don't have RSS yet, we should add that, and make sure to exclude these posts. (3), I don't think orphaned pages have a way of showing up in search engines.

So maybe I should do (a) and we can double-check how it works?

**Comment by chadwhitacre** [comment]
> I don't think orphaned pages have a way of showing up in search engines.

On [Open Path](https://openpath.quest/) I use [a meta tag](https://github.com/chadwhitacre/openpath/blob/a389c5d26ce4c13b06872079cc3fc735bca16ee6/_layouts/default.html#L18-L20) to give myself some confidence that pages won't accidentally leak. I also put [a warning at the top](https://github.com/chadwhitacre/openpath/blob/a389c5d26ce4c13b06872079cc3fc735bca16ee6/_layouts/post.html#L6-L10) just in case. It works great for staging.

**Comment by vladh** [comment]
Sounds good, thanks! #295 addresses the immediate use-case, I'll follow up with a different PR tomorrow to add those other things you mentioned.

**Comment by chadwhitacre** [comment]
Woo-hoo! It's working, thanks! Closing this ticket as my immediate need is resolved. :)

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/14019e7e-24ea-4a9f-b915-0f08634cfa70" />

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/affac709-7206-49e5-aa11-0206d4edb488" />

**Comment by vladh** [comment]
Indexing resolved in #296.
