### ISSUE TITLE
Posit joins the Open Source Pledge

### ISSUE THREAD

**Issue by ivelasq** [opensourcepledge/opensourcepledge.com#297]
Hello! I am submitting an issue to join the open source pledge on behalf of my company, Posit Software, PBC.

* A link to our blog post: https://posit.co/blog/posit-pledge-to-support-open-source/
* A short description of our company, including why we're joining:

> [Posit](https://posit.co/) creates open-source software like RStudio, Shiny, and Quarto to advance data science, research, and technical communication. We're deeply committed to sustaining open-source ecosystems by supporting projects and organizations that drive innovation. Joining the Open Source Pledge reinforces our dedication to the community and our role as stewards of open-source development.

* Our branding materials:
[Posit Branding Materials for Open Source Pledge.zip](https://github.com/user-attachments/files/18213321/Posit.Branding.Materials.for.Open.Source.Pledge.zip)

Thank you for your consideration!

**Comment by vladh** [comment]
@ivelasq It's amazing to have Posit on board, especially since you'll now be our largest member company in terms of developers — I admire your leadership in making Open Source more sustainable! 🎉 

I'll get started on onboarding you right now and let you know if I run into any issues.

**Comment by vladh** [comment]
Done in #298, waiting for review. :)

**Comment by ivelasq** [comment]
@vladh thank you!
