### ISSUE TITLE
Link to / from similar initiatives in other countries? 

### ISSUE THREAD

**Issue by vincib** [opensourcepledge/opensourcepledge.com#63]
Hi OSS pledge !

Thanks for that wonderful idea / project. 
Here in France there were a similar initiative a few years ago, called "copie publique" https://copiepublique.fr/
maybe at some points projects like yours could link to other similar projects in other countries, so that someone coming to the US version could find the French or German one if their company if French or German ;) 

(my company will pledge via copiepublique this year, and I'll ask them if they want to link to osspledge too, once it's up ;) ) 

<3

**Comment by voxpelli** [comment]
Should probably differentiate between countries and regions in this – is there eg. a need to have a different initiative in Europe vs in USA? And what about eg. India? Africa? South America? Middle East?

From a Swedish point of view, we're a far too small country to host anything of this ourselves – doesn't make sense – not enough critical mass – so from a Swedish / Nordic point of view an international or at least European initiative would be preferable.

**Comment by mkurz** [comment]
> From a Swedish point of view, we're a far too small country to host anything of this ourselves – doesn't make sense – not enough critical mass

It's not impossible IMHO - some countries may come up with (of course smaller) initiatives, like Germany recently launched the Sovereign Tech Fund Fellowship program: https://www.sovereigntechfund.de/de/neuigkeiten/fellowship-fuer-maintainerinnen where they directly pay maintainers of OSS projects. It's a pilot program run by the government eventually and if it succeed they may make it bigger.

**Comment by voxpelli** [comment]
> It's not impossible IMHO - some countries may come up with (of course smaller) initiatives, like Germany recently launched the Sovereign Tech Fund Fellowship 

(Just a note – Germany is by far the largest country in Europe – it’s 8-10x the size of eg. Sweden – Sweden is still twice the size of eg Denmark while Denmark is twice the size of eg. Estonia)

**Comment by chadwhitacre** [comment]
I am an e-Resident of Estonia. 😌
