### ISSUE TITLE
Develop a brand identity

### ISSUE THREAD

**Issue by chadwhitacre** [opensourcepledge/opensourcepledge.com#8]
- logo
- colors
- typography
- (self-)certification mark

**Comment by vladh** [comment]
It might be good for the brand identity to include some kind of certification mark, since recognition for participating companies seems important.

![2024-07-12-19-20-08](https://github.com/user-attachments/assets/600c2bf0-782b-4b98-b26c-9705c0cc2d7d)

**Comment by chadwhitacre** [comment]
Agreed @vladh, good examples. @selviano and I have a meeting with Sentry's creative team in a little bit where we'll discuss this and other things, we'll report back.

**Comment by chadwhitacre** [comment]
Current thinking. [Twitter thread](https://x.com/chadwhitacre_/status/1814139960129147192).

![Image](https://github.com/user-attachments/assets/050b9bdf-4550-496f-8701-fcda8a1b4fab)

![Image](https://github.com/user-attachments/assets/95af8178-39cb-4ff4-af88-e051922f9fc7)

![Image](https://github.com/user-attachments/assets/8e178788-1c00-45fc-8da9-591967c96d07)

![Image](https://github.com/user-attachments/assets/cd53853c-9ba9-47f5-aa68-d71d70d2a193)

Getting close, I think?

**Comment by chadwhitacre** [comment]
![Image](https://github.com/user-attachments/assets/887bb684-c489-45a6-975e-a9fcde7cc703)



![Image](https://github.com/user-attachments/assets/e355a553-9cd0-4058-819c-9872a4a9d1a2)

**Comment by chadwhitacre** [comment]
We are dialing in on our logo. Here is the final design we are going to go with!

<img width="888" alt="image" src="https://github.com/user-attachments/assets/df5fb057-576c-468c-a460-3d3444fed4e0">

The heart of the design is the double arrow. It comes from ⇌, the symbol for [chemical equilibrium](https://en.wikipedia.org/wiki/⇌). With the Pledge we are balancing out the equation of maintainers providing software that we all use (forward arrow), by voluntarily paying them for it in return (reverse arrow).

The symbol is framed in a key cap, to symbolize action—"Press the key! Click the button! Take the Pledge! Balance the equation!" The frame has a secondary resonance with a computer monitor or terminal, in keeping with the general software theme.

I'll post image files once they're exported.

**Comment by selviano** [comment]
Pretty substantial proposed update, yet it's so far completely non-controversial among stakeholders. We are considering rebranding (slightly) to just Open Source Pledge. 

The suggestion came today from Greg Kumparak, who in his many years as an editor at TechCrunch learned that jargon in headlines was directly related to decreased engagement on articles (even if the body of the article was of a technical subject). 

Of course anyone who would want to take the Pledge would know what OSS is. But would their CFO know? If 1000 people drove past our billboards, and 100 of them knew what OSS is, how many of the 1000 would know what Open Source is, or at least be familiar with the term and know that it is vaguely a good, popular thing? Certainly more than 100. 

Open to community input about the change, and especially that of @chadwhitacre who is AFK this week. 

![oss-logo-vert-mono-dark](https://github.com/user-attachments/assets/1cfb129f-a3ff-4326-9592-ac511a4627cd)

**Comment by vladh** [comment]
@selviano Big +1 from me, Greg's arguments make a lot of sense. The clearer and simpler the communication the better.

**Comment by Delta456** [comment]
@selviano this makes a lot of clarification for people new to open source and OSS means anything for CFOs!

**Comment by chadwhitacre** [comment]
Rename makes sense to me. I think for consistency to reinforce the brand we should go the whole way and use opensourcepledge.com, etc. (drop osspledge entirely).

**Comment by chadwhitacre** [comment]
Talking with @vladh on weekly steering call. Planning to move forward with this as soon as domain is in hand. We have logo assets as well which I'll add to the repo, then we can close this out!

**Comment by chadwhitacre** [comment]
Domain is in hand. Proceeding with setup ...

**Comment by chadwhitacre** [comment]
Moving to https://github.com/opensourcepledge/osspledge.com/issues/14 for rename. I will close this once I've posted the logos.

**Comment by chadwhitacre** [comment]
Logos/badges in https://github.com/opensourcepledge/opensourcepledge.com/pull/19.

**Comment by chadwhitacre** [comment]
Closing this out with #19! 💃

Gonna pick up in #6.
